---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/appointments":
    get:
      summary: list appointments
      responses:
        '200':
          description: successful
    post:
      summary: create appointment
      responses:
        '200':
          description: successful
  "/api/v1/appointments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show appointment
      responses:
        '200':
          description: successful
    patch:
      summary: update appointment
      responses:
        '200':
          description: successful
    put:
      summary: update appointment
      responses:
        '200':
          description: successful
    delete:
      summary: delete appointment
      responses:
        '200':
          description: successful
  "/api/v1/current_user":
    get:
      summary: list current_users
      responses:
        '200':
          description: successful
  "/api/v1/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: successful
    post:
      summary: create doctor
      responses:
        '200':
          description: successful
  "/api/v1/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show doctor
      responses:
        '200':
          description: successful
    delete:
      summary: delete doctor
      responses:
        '200':
          description: successful
  "/signup/cancel":
    get:
      summary: cancel registration
      responses:
        '200':
          description: successful
  "/signup/sign_up":
    get:
      summary: new registration
      responses:
        '200':
          description: successful
  "/signup/edit":
    get:
      summary: edit registration
      responses:
        '200':
          description: successful
  "/signup":
    patch:
      summary: update registration
      responses:
        '200':
          description: successful
    put:
      summary: update registration
      responses:
        '200':
          description: successful
    delete:
      summary: delete registration
      responses:
        '200':
          description: successful
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/login":
    get:
      summary: new session
      responses:
        '200':
          description: successful
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/logout":
    delete:
      summary: delete session
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
